spring.application.name=jdc-portal-api

spring.datasource.url=jdbc:postgresql://localhost:5432/jdcdb
spring.datasource.username=jdcdb
spring.datasource.password=jdcpwd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=localhost
spring.mail.port=1025

app.jwt.issuer=portal.jdc.com
app.jwt.access-life=10
app.jwt.refresh-life=30