<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.0.5</version>
	</parent>
	<groupId>com.jdc</groupId>
	<artifactId>jdc-portal-api</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>jdc-portal-api</name>
	<packaging>pom</packaging>
	<properties>
		<java.version>25</java.version>
	</properties>
	
	<modules>
		<module>application</module>
		<module>domains</module>
		<module>office-api</module>
		<module>public-api</module>
		<module>student-api</module>
	</modules>
			
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.jdc</groupId>
				<artifactId>application</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.jdc</groupId>
				<artifactId>domains</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.jdc</groupId>
				<artifactId>office-api</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.jdc</groupId>
				<artifactId>public-api</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.jdc</groupId>
				<artifactId>student-api</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	
	<dependencies>
		<dependency>
			<groupId>org.hibernate.orm</groupId>
			<artifactId>hibernate-processor</artifactId>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
			<optional>true</optional>
		</dependency>
	</dependencies>

	<build>
	    <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.hibernate.orm</groupId>
                            <artifactId>hibernate-processor</artifactId>
                            <version>${hibernate.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
	</build>	
</project>
